apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ggzb6qypl-nodejs
  janus-idp.io/tekton: ggzb6qypl-nodejs
  backstage.io/kubernetes-id: ggzb6qypl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ggzb6qypl-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
